.PHONY : help clean figures
.DEFAULT_GOAL := figures

# Figures ==============================================================================================

## figures : makes figures from main text
figures: figures/CIwidthcomparison.png \
figures/comparedensities.png \
figures/site-level-ranefs.png \
figures/spec-level-ranefs.png \
figures/thetaconfusion.png \
figures/validation.png 

# Cleaning Data ========================================================================================

## Download and clean NEON data
data/all_paratax_df.rds data/pinned_df.rds data/expert_df.rds: carabid_data_clean.R
	R CMD BATCH carabid_data_clean.R

## AIS do I need a line with source/jags_input.R as a target? it depends on the cleaned data, but what would the command be?
## ask Hannah HM what to do if a target is its own terminal command

# Analyses =============================================================================================

## Full joint occupancy-classification model output
output/full_jm.rds output/full_jmsumm.rds output/full_theta_summ.rds: \
full_dyn_occ_misclass.R source/jags_input.R full_dyn_occ_misclass_JAGS.txt \
data/all_paratax_df.rds data/pinned_df.rds data/expert_df.rds
	R CMD BATCH full_dyn_occ_misclass.R
	
	
## Figures for full joint occupancy-classification model 
figures/thetaconfusion.png: full_dyn_occ_misclass.R source/jags_input.R \
data/all_paratax_df.rds data/pinned_df.rds data/expert_df.rds
	R CMD BATCH full_dyn_occ_misclass.R

figures/site-level-ranefs.png figures/spec-level-ranefs.png: full_dyn_occ_misclass.R output/full_jm.rds 
	R CMD BATCH full_dyn_occ_misclass.R
	

## Reduced classification model output
output/reduced_jm.rds output/reduced_jmsumm.rds output/reduced_theta_summ.rds: \
reduced_misclass.R source/jags_input.R reduced_misclass_JAGS.txt
	R CMD BATCH reduced_misclass.R
	
	
## Figures comparing full and reduced models
figures/CIwidthcomparison.png: reduced_misclass.R output/full_theta_summ.rds source/jags_input.R \
data/all_paratax_df.rds data/pinned_df.rds data/expert_df.rds
	R CMD BATCH reduced_misclass.R
	
figures/comparedensities.png: reduced_misclass.R output/full_jm.rds output/reduced_jm.rds
	R CMD BATCH reduced_misclass.R

## Validation results 
output/val_full_jm.rds output/val_full_jmsumm.rds output/val_reduced_jm.rds output/val_reduced_jmsumm.rds: \
validation.R source/jags_input.R full_dyn_occ_misclass_JAGS.txt reduced_misclass_JAGS.txt \
data/all_paratax_df.rds data/pinned_df.rds data/expert_df.rds
	R CMD BATCH validation.R
	
figures/validation.png: output/val_full_jm.rds output/val_reduced_jm.rds source/jags_input.R \
data/all_paratax_df.rds data/pinned_df.rds data/expert_df.rds
	R CMD BATCH validation.R


# Makefile Cleaning ====================================================================================
## clean : removes all files generated by this makefile. Individual steps can be cleaned by using remove-figures 
## which deletes all figures and remove-R-outputs which removes saved R-objects and *.Rout files.

clean: remove-figures remove-R-outputs

remove-figures:
	rm -f *.png
	rm -f *.pdf

remove-R-outputs:
	rm -f *.Rout
	rm -f *.RDS


# Makefile help ========================================================================================
## help : displays this help message of targets and their actions
help: Makefile_03
	@echo "Targets to make:"
	@sed -n 's/^##/  /p' Makefile_03
	@echo ""
